#!  /usr/bin/env python

import argparse
import xmltodict
import pprint

def makeLabels(xmldict):
    labels = {}

    for issue in xmldict[u'savaneexport']['item']:
        labels['P: %s' % issue['priority']] = None
        labels['C: %s' % issue['category']] = None
        labels['S: %s' % issue['status']] = None

    # Make the labels at GitHub

    return labels


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Migrate Savannah issues from XML file to GitHub project')
    parser.add_argument('xml_file')
    args = parser.parse_args()





    xml_file = vars(args)['xml_file']
    xml_fh = open(xml_file)
    xml = xml_fh.read()
    xmldict = xmltodict.parse(xml)


    makeLabels(xmldict)


